// Card List
export const CARDS_REQUEST = 'CARDS_REQUEST';
export const CARDS_SUCCESS = 'CARDS_SUCCESS';
export const CARDS_FAILURE = 'CARDS_FAILURE';
export const CARDS_RESET = 'CARDS_RESET';

// Card New
export const CARDS_NEW_REQUEST = 'CARDS_NEW_REQUEST';
export const CARDS_NEW_SUCCESS = 'CARDS_NEW_SUCCESS';
export const CARDS_NEW_FAILURE = 'CARDS_NEW_FAILURE';

// Card Update
export const CARDS_UPDATE_REQUEST = 'CARDS_UPDATE_REQUEST';
export const CARDS_UPDATE_SUCCESS = 'CARDS_UPDATE_SUCCESS';
export const CARDS_UPDATE_FAILURE = 'CARDS_UPDATE_FAILURE';

// Card Delete
export const CARDS_DELETE_REQUEST = 'CARDS_DELETE_REQUEST';
export const CARDS_DELETE_SUCCESS = 'CARDS_DELETE_SUCCESS';
export const CARDS_DELETE_FAILURE = 'CARDS_DELETE_FAILURE';

// Card Move
export const CARDS_MOVE_SUCCESS = 'CARDS_MOVE_SUCCESS';
export const CARDS_MOVE_FAILURE = 'CARDS_MOVE_FAILURE';

// Card Atach Empty List
export const CARDS_ATACH = 'CARDS_ATACH';
