// user CHANGE PASSWORD
export const USER_PASSCHANGE_REQUEST = 'USER_PASSCHANGE_REQUEST';
export const USER_PASSCHANGE_SUCCESS = 'USER_PASSCHANGE_SUCCESS';
export const USER_PASSCHANGE_FAILURE = 'USER_PASSCHANGE_FAILURE';

// user LOAD data
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE';

// user SAVE data
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

// user UPLOAD avatar
export const USER_UPLOAD_REQUEST = 'USER_UPLOAD_REQUEST';
export const USER_UPLOAD_SUCCESS = 'USER_UPLOAD_SUCCESS';
export const USER_UPLOAD_FAILURE = 'USER_UPLOAD_FAILURE';

// user Resets
export const USER_DATA_RESET = 'USER_DATA_RESET';
export const USER_INFO_RESET = 'USER_INFO_RESET';
