// lists
export const LISTS_REQUEST = 'LISTS_REQUEST';
export const LISTS_SUCCESS = 'LISTS_SUCCESS';
export const LISTS_FAILURE = 'LISTS_FAILURE';
export const LISTS_RESET = 'LISTS_RESET';

// New List
export const LISTS_NEW_REQUEST = 'LISTS_NEW_REQUEST';
export const LISTS_NEW_SUCCESS = 'LISTS_NEW_SUCCESS';
export const LISTS_NEW_FAILURE = 'LISTS_NEW_FAILURE';

// Change Card List
export const LISTS_CHANGE_REQUEST = 'LISTS_CHANGE_REQUEST';
export const LISTS_CHANGE_SUCCESS = 'LISTS_CHANGE_SUCCESS';
export const LISTS_CHANGE_FAILURE = 'LISTS_CHANGE_FAILURE';

// Update List
export const LISTS_UPDATE_REQUEST = 'LISTS_UPDATE_REQUEST';
export const LISTS_UPDATE_SUCCESS = 'LISTS_UPDATE_SUCCESS';
export const LISTS_UPDATE_FAILURE = 'LISTS_UPDATE_FAILURE';

export const LISTS_DELETE_REQUEST = 'LISTS_DELETE_REQUEST';
export const LISTS_DELETE_SUCCESS = 'LISTS_DELETE_SUCCESS';
export const LISTS_DELETE_FAILURE = 'LISTS_DELETE_FAILURE';
