// LIST
export const BOARD_REQUEST = 'BOARD_REQUEST';
export const BOARD_SUCCESS = 'BOARD_SUCCESS';
export const BOARD_FAILURE = 'BOARD_FAILURE';
export const BOARD_RESET = 'BOARD_RESET';

// NEW
export const BOARD_NEW_REQUEST = 'BOARD_NEW_REQUEST';
export const BOARD_NEW_SUCCESS = 'BOARD_NEW_SUCCESS';
export const BOARD_NEW_FAILURE = 'BOARD_NEW_FAILURE';

// UPDATE
export const BOARD_UPDATE_REQUEST = 'BOARD_UPDATE_REQUEST';
export const BOARD_UPDATE_SUCCESS = 'BOARD_UPDATE_SUCCESS';
export const BOARD_UPDATE_FAILURE = 'BOARD_UPDATE_FAILURE';

// DELETE
export const BOARD_DEL_REQUEST = 'BOARD_DEL_REQUEST';
export const BOARD_DEL_SUCCESS = 'BOARD_DEL_SUCCESS';
export const BOARD_DEL_FAILURE = 'BOARD_DEL_FAILURE';
